package provision

import (
	"bytes"
	"fmt"
	"maps"
	"os"
	osuser "os/user"
	"path"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/mydevmachine/devmachine/internal/config"
	"github.com/mydevmachine/devmachine/internal/expose"
	"github.com/mydevmachine/devmachine/internal/facts"
	"github.com/mydevmachine/devmachine/internal/packages"
	agentskills "github.com/mydevmachine/devmachine/internal/skills"
	"gopkg.in/yaml.v3"
)

// RemoteDir is where everything a run needs is unpacked on a machine reached
// over SSH.
const RemoteDir = "/opt/devmachine"

// Base is where the bundle lives on a machine: RemoteDir for one reached over
// SSH, or a directory under your computer's own home for one that declares
// `self: true`. /opt is not writable without root on a Mac, so a self
// machine's bundle lives where Homebrew, mise and Claude already do.
func Base(m config.Machine) (string, error) {
	if !m.Self {
		return RemoteDir, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("finding the home directory: %w", err)
	}
	return filepath.Join(home, ".local", "share", "devmachine", "bundle"), nil
}

// inventoryHost is the one host in the generated inventory. It is a fixed name
// rather than the machine's own, so host_vars/<host>.yml has a path that does
// not move when a machine is renamed.
const inventoryHost = "devmachine"

// header says the file is generated, in the comment syntax both YAML and an
// INI-style config understand.
const header = "# Generated by devmachine. Every run rewrites it; do not edit.\n"

// The two directories roles are unpacked into. The operator's own copies come
// first in roles_path, and that ordering is the whole overlay mechanism.
const (
	releaseRoles = "roles"
	localRoles   = "roles.local"
)

// Generate returns the files Ansible needs, keyed by their path under
// RemoteDir. It is GenerateAt with the remote base every machine reached
// over SSH uses.
func Generate(plan packages.MachinePlan) (map[string][]byte, error) {
	return GenerateAt(plan, RemoteDir)
}

// GenerateAt is Generate with the bundle's base directory as an input, so a
// self machine's files point at its own bundle instead of RemoteDir.
//
// It is pure: the same plan and the same base give the same bytes, so a
// change to what a machine is asked to do shows up as a diff rather than as a
// surprise. base is never read from the environment here — Apply resolves it
// before calling in.
func GenerateAt(plan packages.MachinePlan, base string) (map[string][]byte, error) {
	vars, err := hostVars(plan)
	if err != nil {
		return nil, err
	}
	site, err := playbook(plan, base)
	if err != nil {
		return nil, err
	}
	inv, err := inventory(plan.Machine)
	if err != nil {
		return nil, err
	}
	files := map[string][]byte{
		"ansible.cfg":              []byte(ansibleCfg(base)),
		"inventory.ini":            []byte(inv),
		"host_vars/devmachine.yml": vars,
		"site.yml":                 []byte(site),
	}
	for _, f := range routeFiles(plan) {
		if f.change.Content != nil && !f.unresolved {
			files["routes/"+f.workspace+".caddy"] = f.change.Content
		}
	}
	return files, nil
}

// routesByWorkspace groups a plan's routes by the workspace they belong to,
// in the shape RenderWorkspace expects.
func routesByWorkspace(plan packages.MachinePlan) map[string][]expose.Site {
	out := map[string][]expose.Site{}
	for _, r := range plan.Routes {
		out[r.Workspace] = append(out[r.Workspace],
			expose.Site{Host: r.Host, Port: r.Port, Workspace: r.Workspace, Upstream: r.Upstream})
	}
	return out
}

func ansibleCfg(base string) string {
	return header + fmt.Sprintf(`[defaults]
roles_path = %[1]s/%[2]s:%[1]s/%[3]s
inventory = %[1]s/inventory.ini
host_key_checking = False
stdout_callback = default
`, base, localRoles, releaseRoles)
}

// inventory names the one host and no group. A group of the same name would
// work, and Ansible warns about it on every run: "Found both group and host
// with same name". An ungrouped host is already in `all`, and `hosts:
// devmachine` matches it by name.
//
// For a self machine, it also pins ansible_user to the OS user devmachine
// itself runs as. Without it, Ansible's local connection plugin falls back to
// asking the shell who is logged in — and some shells leave LOGNAME set to
// root with USER empty, which sends it looking for /var/root instead of the
// real home directory ("ESTABLISH LOCAL CONNECTION FOR USER: root").
func inventory(m config.Machine) (string, error) {
	line := fmt.Sprintf("%s ansible_connection=local", inventoryHost)
	if m.Self {
		name, _, err := selfIdentity()
		if err != nil {
			return "", err
		}
		line += " ansible_user=" + name
	}
	return header + line + "\n", nil
}

// selfIdentity is the OS user devmachine itself runs as, and that user's home
// directory — read from the operating system, not from USER/LOGNAME, which a
// self machine cannot trust (see inventory).
func selfIdentity() (username, home string, err error) {
	u, err := currentUser()
	if err != nil {
		return "", "", fmt.Errorf("finding the current user: %w", err)
	}
	home, err = os.UserHomeDir()
	if err != nil {
		return "", "", fmt.Errorf("finding the home directory: %w", err)
	}
	return u.Username, home, nil
}

// currentUser is a seam: a test can supply a fake without changing the real
// account devmachine's own tests run as.
var currentUser = osuser.Current

// hostVars is what a recipe reads instead of the CLI's own configuration.
//
// The package list is what will run, not what was typed: a recipe asking
// whether a workspace has something wants the answer `needs` produced.
func hostVars(plan packages.MachinePlan) ([]byte, error) {
	type workspaceVars struct {
		Name     string   `yaml:"name"`
		User     string   `yaml:"user"`
		Packages []string `yaml:"packages"`
	}
	vars := struct {
		Machine           string          `yaml:"devmachine_machine"`
		Workspaces        []workspaceVars `yaml:"devmachine_workspaces"`
		PasswordLoginKeep []string        `yaml:"devmachine_password_login_keep,omitempty"`
	}{Machine: plan.Machine.Name, Workspaces: []workspaceVars{}, PasswordLoginKeep: plan.Machine.PasswordLoginKeep}

	for _, workspace := range plan.Workspaces {
		vars.Workspaces = append(vars.Workspaces, workspaceVars{
			Name:     workspace.Target.Name,
			User:     workspace.Target.LinuxUser,
			Packages: names(workspace.Ordered),
		})
	}

	var root yaml.Node
	if err := root.Encode(vars); err != nil {
		return nil, fmt.Errorf("writing the host variables: %w", err)
	}
	for _, found := range plan.OnMachine.Ordered {
		pairs, err := settingNodes(plan.Machine.Settings, found.Manifest.Name)
		if err != nil {
			return nil, err
		}
		root.Content = append(root.Content, pairs...)
	}

	var body bytes.Buffer
	body.WriteString("---\n" + header)
	encoder := yaml.NewEncoder(&body)
	encoder.SetIndent(2)
	if err := encoder.Encode(&root); err != nil {
		return nil, fmt.Errorf("writing the host variables: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("writing the host variables: %w", err)
	}
	return body.Bytes(), nil
}

// settingNodes names one package's settings the way its recipe already reads
// them: `devmachine_<package>_<key>`, which is the name its own
// defaults/main.yml gives the variable. A setting is a default somebody
// overrode, not a second mechanism, and the recipe cannot tell the difference.
func settingNodes(settings map[string]any, pkg string) ([]*yaml.Node, error) {
	values := config.SettingsFor(settings, pkg)
	named := make(map[string]string, len(values))
	for _, key := range slices.Sorted(maps.Keys(values)) {
		name := ansibleVariable(pkg + "." + key)
		if was, taken := named[name]; taken {
			return nil, fmt.Errorf(
				"the settings %q and %q are both the variable %s: rename one",
				pkg+"."+was, pkg+"."+key, name)
		}
		named[name] = key
	}

	var out []*yaml.Node
	for _, name := range slices.Sorted(maps.Keys(named)) {
		value := &yaml.Node{}
		if err := value.Encode(values[named[name]]); err != nil {
			return nil, fmt.Errorf("writing the setting %s: %w", name, err)
		}
		out = append(out, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: name}, value)
	}
	return out, nil
}

// varsBlock renders one package's settings as a task's own `vars:`.
//
// It is a task option and not one of include_role's: include_role takes a
// fixed set of options and refuses the whole play when it meets one it does
// not know.
func varsBlock(settings map[string]any, pkg string) (string, error) {
	lines, err := settingLines(settings, pkg, "        ")
	if err != nil || lines == "" {
		return "", err
	}
	return "      vars:\n" + lines, nil
}

// settingLines renders one package's settings as the body of a task's `vars:`
// block, indented to sit inside it.
func settingLines(settings map[string]any, pkg, indent string) (string, error) {
	pairs, err := settingNodes(settings, pkg)
	if err != nil {
		return "", err
	}
	if len(pairs) == 0 {
		return "", nil
	}

	var body bytes.Buffer
	encoder := yaml.NewEncoder(&body)
	encoder.SetIndent(2)
	if err := encoder.Encode(&yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", Content: pairs}); err != nil {
		return "", fmt.Errorf("writing the settings of %s: %w", pkg, err)
	}
	if err := encoder.Close(); err != nil {
		return "", fmt.Errorf("writing the settings of %s: %w", pkg, err)
	}

	var out strings.Builder
	for _, line := range strings.Split(strings.TrimRight(body.String(), "\n"), "\n") {
		out.WriteString(indent + line + "\n")
	}
	return out.String(), nil
}

// ansibleVariable turns a setting's key into something Ansible accepts. A dash
// is fine in a package name and never fine in a variable; nor is the dot a
// package may use inside a key of its own.
func ansibleVariable(key string) string {
	return "devmachine_" + strings.NewReplacer("-", "_", ".", "_").Replace(key)
}

func playbook(plan packages.MachinePlan, base string) (string, error) {
	var out strings.Builder
	out.WriteString("---\n" + header)
	if plan.Machine.Self {
		fmt.Fprintf(&out, "- hosts: %s\n  become: false\n", inventoryHost)
	} else {
		fmt.Fprintf(&out, "- hosts: %s\n  become: true\n", inventoryHost)
	}

	forWorkspaces, err := workspaceTasks(plan, false)
	if err != nil {
		return "", err
	}
	contributed, err := skillTasks(plan, base)
	if err != nil {
		return "", err
	}
	// The copies come after the packages that declared them: the account and
	// the tool both have to exist before a session is put where the tool
	// looks for it.
	shared, err := sharingTasks(plan)
	if err != nil {
		return "", err
	}
	tasks := machineTasks(plan) + forWorkspaces + contributed + shared
	// A package that READS a copied session sees nothing on the run that
	// delivered it, so a single pass would leave the machine needing another
	// `sync` — which is the one thing convergence must not do. The packages
	// are idempotent by contract, so the second pass costs a run that reports
	// no change except in whatever was waiting for the copy.
	if shared != "" {
		again, err := workspaceTasks(plan, true)
		if err != nil {
			return "", err
		}
		tasks += again
	}
	extensionsWritten, siteChanges := extensionTasks(plan, base)
	tasks += extensionsWritten
	tasks += routeTasks(plan, base, siteChanges)
	if plan.Machine.Self {
		// A self machine converges on the operator's own Mac. Everything
		// after this task assumes macOS — Homebrew paths, no become — so the
		// guard runs before any of it, not as a check alongside it.
		tasks = darwinGuardTask() + tasks
	}
	if tasks == "" {
		out.WriteString("  tasks: []\n")
		return out.String(), nil
	}
	out.WriteString("  tasks:\n")
	out.WriteString(tasks)
	return out.String(), nil
}

// darwinGuardTask refuses the run before anything else happens, on any
// system other than macOS.
func darwinGuardTask() string {
	return "    - name: refuses anywhere but macOS\n" +
		"      fail:\n        msg: \"a self machine is converged on macOS only; this is {{ ansible_facts['system'] }}\"\n" +
		"      when: ansible_facts['system'] != 'Darwin'\n\n"
}

type contributedSkills struct {
	found      packages.Found
	skills     []agentskills.Skill
	workspaces []packages.Resolved
	// linked holds, per entry of skillLinks, the workspaces that get links.
	linked [][]packages.Resolved
}

// skillLinks lists the harness packages that do not read ~/.agents/skills, and
// the directory under the workspace home where each gets one link per skill.
var skillLinks = []struct {
	pkg   string
	title string
	dir   []string
}{
	{"claude-code", "Claude", agentskills.LinkDir(agentskills.AgentClaude)},
	{"antigravity", "Antigravity", agentskills.LinkDir(agentskills.AgentAntigravity)},
	{"cline", "Cline", agentskills.LinkDir(agentskills.AgentCline)},
}

// skillTasks converges package skill contributions for only the workspaces
// whose resolved package set includes the contributor.
func skillTasks(plan packages.MachinePlan, base string) (string, error) {
	var contributions []contributedSkills
	byPackage := map[string]int{}
	for _, workspace := range plan.Workspaces {
		for _, found := range workspace.Ordered {
			if found.Manifest.Skills == nil {
				continue
			}
			index, ok := byPackage[found.Manifest.Name]
			if !ok {
				discovered, err := agentskills.Discover(filepath.Join(found.Manifest.Path, found.Manifest.Skills.Path))
				if err != nil {
					return "", fmt.Errorf("package %s skills: %w", found.Manifest.Name, err)
				}
				index = len(contributions)
				byPackage[found.Manifest.Name] = index
				contributions = append(contributions, contributedSkills{found: found, skills: discovered, linked: make([][]packages.Resolved, len(skillLinks))})
			}
			contributions[index].workspaces = append(contributions[index].workspaces, workspace)
			for link, harness := range skillLinks {
				if has(workspace, harness.pkg) {
					contributions[index].linked[link] = append(contributions[index].linked[link], workspace)
				}
			}
		}
	}

	var out strings.Builder
	for _, contribution := range contributions {
		writeSkillAccounts(&out, contribution)
		writeSkillDirectories(&out, contribution)
		for _, skill := range contribution.skills {
			writeSkillConvergence(&out, contribution, skill, base)
		}
	}
	return out.String(), nil
}

// skillAccountsVar is where a package's skill tasks keep what the user module
// read about each workspace account. It is one per package because a register
// is per host: with several workspaces in one play, a shared name would hold
// the last account read.
func skillAccountsVar(pkg string) string {
	return "devmachine_skill_" + strings.NewReplacer("-", "_", ".", "_").Replace(pkg) + "_accounts"
}

// accountField is one field of the account the user module read for this
// loop's workspace, or fallback when there is none yet, as in a dry run
// before the account exists.
func accountField(accounts, field, fallback string) string {
	return "{{ " + accounts + ".results | selectattr('devmachine_workspace.user', 'equalto', devmachine_workspace.user)" +
		" | map(attribute='" + field + "', default=none) | reject('none') | first | default(" + fallback + ") }}"
}

// workspaceHome and workspaceGroup are a workspace account's home and primary
// group as the machine has them: /home/<user> and the user's own group on
// Linux, /Users/<user> and staff on a Mac, which has no group per user. The
// group is the numeric gid, which needs no group name to exist.
func workspaceHome(accounts string) string {
	return accountField(accounts, "home",
		"('/Users/' if ansible_facts['system'] == 'Darwin' else '/home/') ~ devmachine_workspace.user")
}

func workspaceGroup(accounts string) string {
	return accountField(accounts, "group", "devmachine_workspace.user")
}

// writeSkillAccounts reads each workspace account before any skill task
// names its home. Check mode, so it never creates or changes an account.
func writeSkillAccounts(out *strings.Builder, contribution contributedSkills) {
	name := contribution.found.Manifest.Name
	fmt.Fprintf(out, "    - name: %s reads the workspace accounts\n", name)
	out.WriteString("      user:\n        name: \"{{ devmachine_workspace.user }}\"\n")
	out.WriteString("      check_mode: true\n      changed_when: false\n")
	fmt.Fprintf(out, "      register: %s\n", skillAccountsVar(name))
	writeSkillLoop(out, contribution.workspaces, false)
	fmt.Fprintf(out, "      tags: [%s]\n\n", name)
}

func writeSkillDirectories(out *strings.Builder, contribution contributedSkills) {
	name := contribution.found.Manifest.Name
	home, group := workspaceHome(skillAccountsVar(name)), workspaceGroup(skillAccountsVar(name))
	for _, dir := range []struct {
		title string
		path  string
		mode  string
	}{
		{"canonical skill directory", home + "/.agents/skills", "0755"},
		{"skill ownership directory", home + "/.local/state/devmachine/skills", "0700"},
	} {
		fmt.Fprintf(out, "    - name: %s prepares the %s\n", name, dir.title)
		fmt.Fprintf(out, "      file:\n        path: %q\n        state: directory\n", dir.path)
		out.WriteString("        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"" + group + "\"\n")
		fmt.Fprintf(out, "        mode: %q\n", dir.mode)
		writeSkillLoop(out, contribution.workspaces, false)
		fmt.Fprintf(out, "      tags: [%s]\n\n", name)
	}
	for link, harness := range skillLinks {
		workspaces := contribution.linked[link]
		if len(workspaces) == 0 {
			continue
		}
		// Ansible would create missing parents as root; each level is created
		// on its own so the workspace user owns all of them. Parents get no
		// mode, so one that already exists keeps its own.
		for level := 1; level < len(harness.dir); level++ {
			parent := strings.Join(harness.dir[:level], "/")
			fmt.Fprintf(out, "    - name: %s prepares ~/%s for %s skills\n", name, parent, harness.title)
			fmt.Fprintf(out, "      file:\n        path: %q\n        state: directory\n", home+"/"+parent)
			out.WriteString("        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"" + group + "\"\n")
			writeSkillLoop(out, workspaces, false)
			fmt.Fprintf(out, "      tags: [%s]\n\n", name)
		}
		fmt.Fprintf(out, "    - name: %s prepares the %s skill directory\n", name, harness.title)
		fmt.Fprintf(out, "      file:\n        path: %q\n        state: directory\n", home+"/"+strings.Join(harness.dir, "/"))
		out.WriteString("        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"" + group + "\"\n        mode: \"0755\"\n")
		writeSkillLoop(out, workspaces, false)
		fmt.Fprintf(out, "      tags: [%s]\n\n", name)
	}
}

func writeSkillConvergence(out *strings.Builder, contribution contributedSkills, skill agentskills.Skill, base string) {
	pkg := contribution.found.Manifest.Name
	sourceID := pkg
	home, group := workspaceHome(skillAccountsVar(pkg)), workspaceGroup(skillAccountsVar(pkg))
	destination := home + "/.agents/skills/" + skill.Name
	owner := home + "/.local/state/devmachine/skills/" + skill.Name + ".owner"
	variable := strings.NewReplacer("-", "_", ".", "_").Replace(pkg + "_" + skill.Name)
	destinationResult := "devmachine_skill_" + variable + "_destination"
	ownerResult := "devmachine_skill_" + variable + "_owner"
	contentResult := "devmachine_skill_" + variable + "_owner_content"

	fmt.Fprintf(out, "    - name: %s checks the %s destination\n", pkg, skill.Name)
	fmt.Fprintf(out, "      stat:\n        path: %q\n", destination)
	fmt.Fprintf(out, "      register: %s\n", destinationResult)
	writeSkillLoop(out, contribution.workspaces, true)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s checks the %s ownership record\n", pkg, skill.Name)
	fmt.Fprintf(out, "      stat:\n        path: %q\n", owner)
	fmt.Fprintf(out, "      register: %s\n", ownerResult)
	writeSkillLoop(out, contribution.workspaces, true)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s reads the %s ownership record\n", pkg, skill.Name)
	fmt.Fprintf(out, "      slurp:\n        src: %q\n", owner)
	fmt.Fprintf(out, "      register: %s\n", contentResult)
	fmt.Fprintf(out, "      when: %s.results[devmachine_skill_index].stat.exists\n", ownerResult)
	writeSkillLoop(out, contribution.workspaces, true)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s refuses an unmanaged %s collision\n", pkg, skill.Name)
	fmt.Fprintf(out, "      fail:\n        msg: %q\n", "skill "+skill.Name+" already exists and is not owned by "+sourceID)
	out.WriteString("      when:\n")
	fmt.Fprintf(out, "        - %s.results[devmachine_skill_index].stat.exists\n", destinationResult)
	fmt.Fprintf(out, "        - not %s.results[devmachine_skill_index].stat.exists or ((%s.results[devmachine_skill_index].content | default('') | b64decode | trim) != %q)\n", ownerResult, contentResult, sourceID)
	writeSkillLoop(out, contribution.workspaces, true)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s installs the %s skill\n", pkg, skill.Name)
	fmt.Fprintf(out, "      copy:\n        src: %q\n        dest: %q\n", RolePath(base, contribution.found.Source, pkg, contribution.found.Manifest.Skills.Path, skill.Name)+"/", destination+"/")
	out.WriteString("        remote_src: true\n        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"" + group + "\"\n        mode: preserve\n")
	writeSkillLoop(out, contribution.workspaces, false)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s records ownership of the %s skill\n", pkg, skill.Name)
	fmt.Fprintf(out, "      copy:\n        content: %q\n        dest: %q\n", sourceID+"\n", owner)
	out.WriteString("        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"" + group + "\"\n        mode: \"0600\"\n")
	writeSkillLoop(out, contribution.workspaces, false)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	for link, harness := range skillLinks {
		workspaces := contribution.linked[link]
		if len(workspaces) == 0 {
			continue
		}
		src := strings.Repeat("../", len(harness.dir)) + ".agents/skills/" + skill.Name
		dest := home + "/" + strings.Join(harness.dir, "/") + "/" + skill.Name
		fmt.Fprintf(out, "    - name: %s links the %s skill for %s\n", pkg, skill.Name, harness.title)
		fmt.Fprintf(out, "      file:\n        src: %q\n        dest: %q\n        state: link\n", src, dest)
		out.WriteString("        force: \"{{ ansible_check_mode }}\"\n")
		out.WriteString("        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"" + group + "\"\n")
		writeSkillLoop(out, workspaces, false)
		fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)
	}
}

func writeSkillLoop(out *strings.Builder, workspaces []packages.Resolved, indexed bool) {
	out.WriteString("      loop:\n")
	for _, workspace := range workspaces {
		fmt.Fprintf(out, "        - {name: %q, user: %q}\n", workspace.Target.Name, workspace.Target.LinuxUser)
	}
	out.WriteString("      loop_control:\n        loop_var: devmachine_workspace\n")
	if indexed {
		out.WriteString("        index_var: devmachine_skill_index\n")
	}
}

func machineTasks(plan packages.MachinePlan) string {
	var out strings.Builder
	for _, found := range plan.OnMachine.Ordered {
		name := found.Manifest.Name
		fmt.Fprintf(&out, "    - name: %s\n", name)
		out.WriteString(includeRole(name))
		fmt.Fprintf(&out, "      tags: [%s]\n\n", name)
	}
	return out.String()
}

// workspaceTasks runs each workspace package once, looping over the
// workspaces that asked for it.
//
// The packages are ordered by walking the workspaces in turn and taking each
// name the first time it appears. That keeps `needs` satisfied: a package is
// always preceded by what it needs inside every workspace that has it, so the
// first appearance of a need is never later than the first appearance of the
// package that needs it.
func workspaceTasks(plan packages.MachinePlan, again bool) (string, error) {
	var (
		out   strings.Builder
		order []string
		seen  = map[string]bool{}
	)
	for _, workspace := range plan.Workspaces {
		for _, found := range workspace.Ordered {
			if name := found.Manifest.Name; !seen[name] {
				seen[name] = true
				order = append(order, name)
			}
		}
	}

	for _, name := range order {
		groups, err := groupBySettings(plan, name)
		if err != nil {
			return "", err
		}
		for _, group := range groups {
			fmt.Fprintf(&out, "    - name: %s\n", group.title(name, again))
			out.WriteString(includeRole(name))
			out.WriteString(group.vars)
			out.WriteString("      loop:\n")
			for _, workspace := range group.workspaces {
				fmt.Fprintf(&out, "        - {name: %q, user: %q}\n",
					workspace.Target.Name, workspace.Target.LinuxUser)
			}
			// loop_var, rather than `vars: devmachine_workspace: "{{ item }}"`.
			// A role is free to have loops of its own, and any of them would
			// rebind `item` — so the workspace would quietly become whatever
			// the inner loop was iterating. Naming the variable here means no
			// package can get it wrong, and none has to remember to try.
			out.WriteString("      loop_control:\n        loop_var: devmachine_workspace\n")
			fmt.Fprintf(&out, "      tags: [%s]\n\n", name)
		}
	}
	return out.String(), nil
}

// group is the workspaces one include_role covers: those that give a package
// the same settings, which is usually all of them and no settings at all.
type group struct {
	vars       string
	workspaces []packages.Resolved
}

func (g group) title(pkg string, again bool) string {
	if again {
		return pkg + " again, now that the shared logins are in place"
	}
	if g.vars == "" {
		return pkg + " for each workspace that declares it"
	}
	who := make([]string, 0, len(g.workspaces))
	for _, workspace := range g.workspaces {
		who = append(who, workspace.Target.Name)
	}
	return pkg + " for " + strings.Join(who, ", ")
}

// groupBySettings splits the workspaces that install a package by what they
// set on it, in the order they appear. One loop cannot carry two values for
// one variable, so a workspace that overrides something gets a task of its
// own; everybody else keeps sharing one.
func groupBySettings(plan packages.MachinePlan, pkg string) ([]group, error) {
	var (
		groups []group
		at     = map[string]int{}
	)
	for _, workspace := range plan.Workspaces {
		if !has(workspace, pkg) {
			continue
		}
		vars, err := varsBlock(workspace.Target.Settings, pkg)
		if err != nil {
			return nil, fmt.Errorf("workspace %q: %w", workspace.Target.Name, err)
		}
		index, known := at[vars]
		if !known {
			index = len(groups)
			at[vars] = index
			groups = append(groups, group{vars: vars})
		}
		groups[index].workspaces = append(groups[index].workspaces, workspace)
	}
	return groups, nil
}

// extensionTasks copy each contribution into the directory its provider
// opened, then remove whichever file the previous lock recorded writing that
// the current plan no longer writes — the file a package left behind when it
// left the configuration. They run last, after the package that creates the
// directory, and report the registered results that can change what Caddy
// serves — a copy into the sites directory, the removal task — so routeTasks
// makes its caddy reload watch them too.
func extensionTasks(plan packages.MachinePlan, base string) (string, []string) {
	found := map[string]packages.Found{}
	for _, resolved := range append([]packages.Resolved{plan.OnMachine}, plan.Workspaces...) {
		for _, f := range resolved.Ordered {
			found[f.Manifest.Name] = f
		}
	}

	var out strings.Builder
	var siteChanges []string
	current := map[string]bool{}
	for _, extension := range plan.Extensions {
		from := found[extension.From]
		source := path.Join(base, rolesDir(from.Source), extension.From, extension.Source)
		destination := extension.Path()
		current[destination] = true

		where := extension.Point
		if extension.Scope == packages.ScopeWorkspace {
			where += " for " + extension.Target
		}

		fmt.Fprintf(&out, "    - name: %s extends %s\n", extension.From, where)
		fmt.Fprintf(&out, "      copy:\n        src: %q\n        dest: %q\n", source, destination)
		out.WriteString("        owner: root\n        group: root\n        mode: \"0644\"\n")
		if plan.SitesDir != "" && extension.Into == plan.SitesDir {
			registered := fmt.Sprintf("devmachine_extension_%d", len(siteChanges))
			fmt.Fprintf(&out, "      register: %s\n", registered)
			siteChanges = append(siteChanges, registered)
		}
		fmt.Fprintf(&out, "      tags: [%s]\n\n", extension.From)
	}

	var removed []string
	for _, p := range plan.PreviousExtensions {
		if !current[p] {
			removed = append(removed, p)
		}
	}
	sort.Strings(removed)
	if len(removed) == 0 {
		return out.String(), siteChanges
	}

	out.WriteString("    - name: files a package left when it left the plan\n      file:\n")
	out.WriteString("        path: \"{{ item }}\"\n        state: absent\n      loop:\n")
	for _, p := range removed {
		fmt.Fprintf(&out, "        - %q\n", p)
	}
	out.WriteString("      register: devmachine_extensions_removed\n      tags: [extensions]\n\n")
	return out.String(), append(siteChanges, "devmachine_extensions_removed")
}

// routeTasks put every workspace's routes file where caddy reads it, take
// away the one-host files the old `expose` wrote for a host the configuration
// now owns — Caddy refuses a reload that names one host twice — and the file
// of a workspace with no route left. They run after every package, so caddy
// has made sites.d, and reload Caddy only when something changed.
//
// siteChanges names the results extensionTasks registered earlier in the
// play: that reload has to watch them too, or a package changing or leaving
// its site file would do it without Caddy ever noticing.
func routeTasks(plan packages.MachinePlan, base string, siteChanges []string) string {
	if plan.SitesDir == "" {
		return ""
	}
	var written, absent []string
	dest := map[string]string{}
	for _, f := range routeFiles(plan) {
		switch {
		case f.unresolved:
		case f.change.Content == nil:
			absent = append(absent, f.change.Path)
		default:
			written = append(written, f.workspace)
			dest[f.workspace] = f.change.Path
			absent = append(absent, f.change.Stale...)
		}
	}
	sort.Strings(written)

	var out strings.Builder
	if len(written) > 0 {
		out.WriteString("    - name: routes from the configuration\n      copy:\n")
		out.WriteString("        src: \"{{ item.src }}\"\n        dest: \"{{ item.dest }}\"\n")
		fmt.Fprintf(&out, "        owner: %s\n        group: %s\n        mode: %q\n      loop:\n",
			routeFileOwner, routeFileGroup, routeFileMode)
		for _, name := range written {
			fmt.Fprintf(&out, "        - {src: %q, dest: %q}\n", path.Join(base, "routes", name+".caddy"), dest[name])
		}
		out.WriteString("      register: devmachine_routes_written\n      tags: [routes]\n\n")
	}
	if len(absent) > 0 {
		out.WriteString("    - name: files the configuration no longer owns\n      file:\n")
		out.WriteString("        path: \"{{ item.path }}\"\n        state: absent\n      loop:\n")
		for _, p := range absent {
			fmt.Fprintf(&out, "        - {path: %q}\n", p)
		}
		out.WriteString("      register: devmachine_routes_removed\n      tags: [routes]\n\n")
	}
	if len(written) == 0 && len(absent) == 0 && len(siteChanges) == 0 {
		return ""
	}
	out.WriteString("    - name: reload caddy for the routes\n      systemd:\n        name: caddy\n        state: reloaded\n")
	when := "(devmachine_routes_written is defined and devmachine_routes_written is changed) or " +
		"(devmachine_routes_removed is defined and devmachine_routes_removed is changed)"
	for _, registered := range siteChanges {
		when += fmt.Sprintf(" or (%s is defined and %s is changed)", registered, registered)
	}
	// The reload goes through systemd on Linux. A Mac runs Caddy under
	// launchd, so there it goes through Caddy's own admin endpoint, with the
	// package managers' directories that a play's shell does not have.
	out.WriteString("      when: ansible_facts['system'] == 'Linux' and (" + when + ")\n")
	out.WriteString("      tags: [routes]\n\n")
	fmt.Fprintf(&out, "    - name: reload caddy for the routes on a Mac\n      shell: PATH=\"%s:$PATH\" caddy reload --config %s --adapter caddyfile\n",
		strings.Join(facts.MacPath(), ":"), expose.Caddyfile)
	out.WriteString("      when: ansible_facts['system'] == 'Darwin' and (" + when + ")\n")
	out.WriteString("      tags: [routes]\n\n")
	return out.String()
}

// includeRole is a dynamic include, and the apply block is not optional:
// without it the role's own tasks do not inherit the tag, so `--tags docker`
// includes the role and then skips everything in it.
func includeRole(name string) string {
	return fmt.Sprintf("      include_role:\n        name: %s\n        apply:\n          tags: [%s]\n",
		name, name)
}

// RolePath names a file inside a package, on the machine.
//
// It is exported because the CLI reaches into a package from outside this
// package — a DNS provider's entrypoint, a credential's helper — and the
// overlay rule that picks roles.local over roles must have exactly one
// implementation. Two would be one rule nobody remembers to change twice.
func RolePath(base, source, name string, rest ...string) string {
	return path.Join(append([]string{base, rolesDir(source), name}, rest...)...)
}

// rolesDir is where a package is unpacked, which is what decides whether the
// operator's copy or the published one runs.
func rolesDir(source string) string {
	if source == packages.SourceLocal {
		return localRoles
	}
	return releaseRoles
}

func has(resolved packages.Resolved, name string) bool {
	for _, found := range resolved.Ordered {
		if found.Manifest.Name == name {
			return true
		}
	}
	return false
}

func names(found []packages.Found) []string {
	out := make([]string, 0, len(found))
	for _, f := range found {
		out = append(out, f.Manifest.Name)
	}
	return out
}
